export APP_NAME="onchain-summer-2024"
export NEW_RELIC_LICENSE_KEY="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
export DB_HOSTNAME="127.0.0.1"
export DB_PASSWORD="XXXXXXXXXXXXXXXXXXXXXXXXX"
export DB_USERNAME="XXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

go run main.go
